### ISSUE TITLE
[BUG:macOS] token change to native EVM token on macOS

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1752]
**Describe the bug**
The bug where when sending and preselecting a token on any EVM chain changes to the selection of the native token still happens on macOS once after the first start of the app. see issue #1624 as reference

**To Reproduce**
1. Use mac and select any token on any EVM chain
2. Click on send when in detail view of this token
3. See error when filling out `address` and `amount`

**Expected behavior**
Keep preselection of token

System:

 - Version 1.10.1

**Comment by FerrariGen** [comment]
@realpaaao For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Help SUPPORT](https://generalhub-issue.web.app/).
If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by Rockindash** [comment]
@realpaaao I am currently on version 1.10.2 and am unable to reproduce it. Can you please pull the changes and try again. It seems that it was fixed in

**Comment by realpaaao** [comment]
@Rockindash it still happens for me on my mac with latest 1.10.2 installed from GH.
