### ISSUE TITLE
[CHANGE] On asset amount fields only present num keyboard

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#2064]
We should present only the number keyboard when user opens any `AMOUNT` textfield for assets.

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/2110

**Comment by MareskoY** [comment]
@enriquesouza for send flow amount field still:
1. opens text keyboard
2. possible to enter text 
3. 1,5 doesn't work as it should be based on that https://github.com/vultisig/vultisig-ios/pull/2110 

![Image](https://github.com/user-attachments/assets/de66ed63-acc7-41f5-9f13-24c31538e059)
![Image](https://github.com/user-attachments/assets/139e8539-7412-43f6-9e6b-6423eaa6eef3)

**Comment by enriquesouza** [comment]
This is fixed using the decimal places PR

**Comment by MareskoY** [comment]
was tested with 1.71.1

but still exist this issue 

https://github.com/vultisig/vultisig-ios/issues/2169
